export default function Footer() {
  return (
    <footer
      className="
        py-12
        bg-[#000000]
        border-t border-gray-800
      "
    >
      <div
        className="
          container
          mx-auto px-6
        "
      >
        <div
          className="
            grid grid-cols-1
            gap-8
            md:grid-cols-4
          "
        >
          <div>
            <h3
              className="
                mb-4
                text-white text-xl font-bold
              "
            >
              E-commerce
            </h3>
            <p
              className="
                mb-4
                text-gray-400
              "
            >
              Your gateway to the future of technology. Premium products,
              exceptional service.
            </p>
          </div>

          <div>
            <h4
              className="
                mb-4
                text-white font-semibold
              "
            >
              Quick Links
            </h4>
            <ul
              className="
                space-y-2
              "
            >
              <li>
                <a
                  href="/about"
                  className="
                    text-gray-400
                    transition-colors
                    hover:text-white
                  "
                >
                  About Us
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="
                    text-gray-400
                    transition-colors
                    hover:text-white
                  "
                >
                  Products
                </a>
              </li>
              <li>
                <a
                  href="/about"
                  className="
                    text-gray-400
                    transition-colors
                    hover:text-white
                  "
                >
                  Support
                </a>
              </li>
              <li>
                <a
                  href="/about"
                  className="
                    text-gray-400
                    transition-colors
                    hover:text-white
                  "
                >
                  Contact
                </a>
              </li>
            </ul>
          </div>

          <div>
            <h4
              className="
                mb-4
                text-white font-semibold
              "
            >
              Categories
            </h4>
            <ul
              className="
                space-y-2
              "
            >
              <li>
                <a
                  href="#"
                  className="
                    text-gray-400
                    transition-colors
                    hover:text-white
                  "
                >
                  Electronics
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="
                    text-gray-400
                    transition-colors
                    hover:text-white
                  "
                >
                  Gaming
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="
                    text-gray-400
                    transition-colors
                    hover:text-white
                  "
                >
                  Audio
                </a>
              </li>
              <li>
                <a
                  href="#"
                  className="
                    text-gray-400
                    transition-colors
                    hover:text-white
                  "
                >
                  Monitors
                </a>
              </li>
            </ul>
          </div>

          <div>
            <h4
              className="
                mb-4
                text-white font-semibold
              "
            >
              Connect
            </h4>
            <div
              className="
                flex
                space-x-4
              "
            >
              <a
                href="#"
                className="
                  text-gray-400
                  transition-colors
                  hover:text-white
                "
              >
                Facebook
              </a>
              <a
                href="#"
                className="
                  text-gray-400
                  transition-colors
                  hover:text-white
                "
              >
                Twitter
              </a>
              <a
                href="#"
                className="
                  text-gray-400
                  transition-colors
                  hover:text-white
                "
              >
                Instagram
              </a>
            </div>
          </div>
        </div>

        <div
          className="
            mt-8 pt-8
            text-center
            border-t border-gray-800
          "
        >
          <p
            className="
              text-gray-400
            "
          >
            &copy; 2025 E-commerce. All rights reserved.
          </p>
        </div>
      </div>
    </footer>
  );
}
